# Generated by Django 5.2.8 on 2026-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
